# Generated by Django 4.0.4 on 2022-05-29 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reporting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=100)),
                ('project_address', models.CharField(max_length=300)),
                ('client', models.CharField(max_length=50)),
                ('building_type', models.CharField(max_length=50)),
                ('active', models.BooleanField(default=1)),
            ],
        ),
    ]
