# Generated by Django 4.0.4 on 2022-05-29 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporting',
            name='building_height',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reporting',
            name='number_of_stairs',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reporting',
            name='project_value',
            field=models.BigIntegerField(default=0),
        ),
    ]
