# Generated by Django 4.0.4 on 2022-05-30 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application1', '0002_reporting_building_height_reporting_number_of_stairs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporting',
            name='report_run',
            field=models.BooleanField(default=0),
        ),
    ]
