# Generated by Django 4.0.4 on 2022-06-05 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application1', '0002_rename_client_reporting_client_company_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reporting',
            name='client',
        ),
        migrations.AddField(
            model_name='reporting',
            name='client_company',
            field=models.CharField(default='', max_length=50),
        ),
    ]
