# Generated by Django 4.0.4 on 2022-05-30 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application1', '0003_reporting_report_run'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reporting',
            old_name='client',
            new_name='client_company',
        ),
        migrations.AddField(
            model_name='reporting',
            name='client_representative',
            field=models.CharField(default='mr Architect', max_length=100),
        ),
    ]
