# Generated by Django 4.0.4 on 2022-06-05 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application1', '0003_remove_reporting_client_reporting_client_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporting',
            name='report_issued',
            field=models.BooleanField(default=0),
        ),
    ]
