# Generated by Django 4.0.4 on 2022-06-05 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application1', '0004_reporting_report_issued'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporting',
            name='invoice_generated',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='reporting',
            name='invoice_issued',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='reporting',
            name='assigned_engineer',
            field=models.CharField(choices=[('Codrin Florescu', 'Codrin Florescu')], default='NA', max_length=45),
        ),
    ]
