# Generated by Django 4.0.4 on 2022-05-30 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application1', '0004_rename_client_reporting_client_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporting',
            name='request_date',
            field=models.CharField(default='2022-05-30', max_length=100),
        ),
    ]
