# Generated by Django 4.0.4 on 2022-06-01 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application1', '0005_reporting_request_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporting',
            name='request_date',
            field=models.CharField(default='2022-06-01', max_length=100),
        ),
    ]
