# Generated by Django 4.0.4 on 2022-06-02 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application1', '0006_alter_reporting_request_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporting',
            name='request_date',
            field=models.CharField(default='2022-06-02', max_length=100),
        ),
    ]
