# Generated by Django 4.0.4 on 2022-06-02 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application1', '0007_alter_reporting_request_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporting',
            name='quote_issued',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='reporting',
            name='client_representative',
            field=models.CharField(max_length=100),
        ),
    ]
