# Generated by Django 4.0.4 on 2022-06-02 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application1', '0008_reporting_quote_issued_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporting',
            name='quote_accepted',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='reporting',
            name='report_generated',
            field=models.BooleanField(default=0),
        ),
    ]
