# Generated by Django 4.0.4 on 2022-06-02 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Application1', '0009_reporting_quote_accepted_reporting_report_generated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reporting',
            old_name='report_run',
            new_name='quote_produced',
        ),
    ]
