# Generated by Django 4.0.4 on 2022-06-05 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Application1', '0012_alter_reporting_request_date'),
        ('Application2', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='revenues',
            name='project_name',
        ),
        migrations.AddField(
            model_name='revenues',
            name='reporting',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Application1.reporting'),
        ),
    ]
