# Generated by Django 4.0.4 on 2022-06-05 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application2', '0004_revenues_id_alter_revenues_reporting'),
    ]

    operations = [
        migrations.AddField(
            model_name='revenues',
            name='name',
            field=models.CharField(default='abc', max_length=20),
        ),
    ]
