# Generated by Django 4.0.4 on 2022-06-05 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Application2', '0005_revenues_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Revenues',
        ),
    ]
